# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='Description',
            field=models.TextField(default='', max_length=250, verbose_name='Describe the trainings you have acquired'),
        ),
    ]
