# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20160126_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='job_opening',
        ),
        migrations.RemoveField(
            model_name='selectivequestions',
            name='job_opening',
        ),
        migrations.AddField(
            model_name='jobopenings',
            name='general_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Questionnaire'),
        ),
        migrations.AddField(
            model_name='jobopenings',
            name='job_specific_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.SelectiveQuestions'),
        ),
    ]
