# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rsa_succesful_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='succesful_applicant',
        ),
    ]
