# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20160126_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopenings',
            name='general_questions',
        ),
        migrations.RemoveField(
            model_name='jobopenings',
            name='job_specific_questions',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='job_opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.JobOpenings'),
        ),
        migrations.AddField(
            model_name='selectivequestions',
            name='job_opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.JobOpenings'),
        ),
    ]
