# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20160127_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='job_opening',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='application.JobOpenings'),
        ),
    ]
