# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20160127_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MBA', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Do you have an MBA?')),
                ('Formal_Business_Training', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Do you have formal training in Business development')),
                ('Description', models.TextField(default='', max_length=250, verbose_name='Describe the trainings you have acquired')),
                ('Employment_Status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Are you currently employed')),
                ('Employment_Fields', models.CharField(choices=[('Software Sales - 5 years and above', 'Software Sales - 5 years and above'), ('Software Business Development - 5 years and above', 'Software Business Development - 5 years and above')], max_length=20, verbose_name='Select any of the following fields that represent your experience')),
                ('Client_acquisition', models.TextField()),
                ('Client_retention', models.TextField()),
                ('Equity', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Do you care about having equity?')),
                ('Salary_for_equity', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Are you willing to trade a portion of salary for equity? ')),
                ('Job_Salary', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Can you live on N250,000 or less for the next 3-6 months?')),
                ('Job_Time', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='I just want a 9-5 job to pay the bills')),
                ('Told_What_to_do', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='I like to be told what to do')),
                ('Entrepreneur', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='I am an entrepreneur at heart')),
                ('Dislikes', models.CharField(choices=[('Igbos', 'Igbos'), ('Yorubas', 'Yorubas'), ('Northerners', 'Northerners'), ('Southerners', 'Southerners'), ('None', 'None')], max_length=100, verbose_name='Who do you dislike the most?')),
                ('Get_along_with', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('All', 'All')], max_length=10, verbose_name='Who do you get along with')),
                ('Gay_people', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Gay people are disgusting and should be put in jail')),
                ('Muslims', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='I cannot stand muslims')),
                ('Christians', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='Christians and others are infidels')),
                ('job_opening', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='application.JobOpenings')),
            ],
        ),
        migrations.RemoveField(
            model_name='choices',
            name='question',
        ),
        migrations.RemoveField(
            model_name='selectivequestions',
            name='job_opening',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='SelectiveQuestions',
        ),
    ]
