# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20160127_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='Formal_Finance_Training',
            new_name='Formal_Training',
        ),
        migrations.RenameField(
            model_name='rsa',
            old_name='Formal_Business_Training',
            new_name='Formal_Training',
        ),
    ]
