# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20160128_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='Description',
            field=models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Describe the trainings you have acquired'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='Employment_Fields',
            field=models.CharField(choices=[('Investment Banking - 5 years and above', 'Investment Banking - 5 years and above'), ('Mergers and Acquisitions and Stock Trading - 5 years and above', 'Mergers and Acquisitions and Stock Trading - 5 years and above'), ('Previous CFO Position - 3 years and above', 'Previous CFO Position - 3 years and above'), ('Previous CEO Position - 3 years and above', 'Previous CEO Position - 3 years and above'), ('Senior level Auditor - 3 years and above', 'Senior level Auditor - 3 years and above')], max_length=200, verbose_name='Select any of the following fields that represent your experience'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='Employment_Status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Are you currently employed'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='Client_acquisition',
            field=models.TextField(verbose_name='Tell us how you intend to approach client acquisition'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='Client_retention',
            field=models.TextField(verbose_name='Tell us how you intend to approach client retention'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='Description',
            field=models.TextField(blank=True, default='', max_length=250, null=True, verbose_name='Describe the trainings you have acquired'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='Employment_Fields',
            field=models.CharField(choices=[('Software Sales - 5 years and above', 'Software Sales - 5 years and above'), ('Software Business Development - 5 years and above', 'Software Business Development - 5 years and above')], max_length=200, verbose_name='Select any of the following fields that represent your experience'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='Employment_Status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=250, verbose_name='Are you currently employed'),
        ),
        migrations.AlterField(
            model_name='rsa',
            name='Formal_Training',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=250, verbose_name='Do you have formal training in Business development'),
        ),
    ]
